name: CI

on:
  push:
    branches: [ main ]
  pull_request:

env:
  NIX_PATH: "nixpkgs=channel:nixos-25.05"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Build release binary
        run: nix-shell --pure --run "just build"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Run clippy lint
        run: nix-shell --pure --run "just lint"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Execute unit tests
        run: nix-shell --pure --run "just test"

  reflow-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Run reflow on test catalogue
        run: nix-shell --pure --run "just reflow-data"

  compare-data:
    needs: reflow-data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Compare original vs reflowed corpus (non-fatal)
        continue-on-error: true
        run: nix-shell --pure --run "just compare-data"

  nix-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Build via default.nix and assert binary runs
        run: nix-shell --pure --run "just nix-test" 